### ISSUE TITLE
Utilisation de booléens

### ISSUE THREAD

**Issue by simonparisot** [betagouv/publicodes#1]
Bonjour,
Nous cherchons à utiliser publicodes (grammaire et engine) dans un projet financier, et je me heurte à des difficultés pour comprendre la grammaire de base : comment définir et utiliser une variable booléenne en yaml avec le studio : https://publi.codes/studio/ ?

Sur un exemple très simple, ci-dessous, le studio ne renvoie aucun résultat, que ce soit pour la variable a ou b :
```
a:
  formule: b
  exemples:
    - situation:
        b: oui
      valeur attendue: true
    - situation:
        b: non
      valeur attendue: false

b:
  formule: oui
  exemples:
    - valeur attendue: true
```

Pourriez-vous m'indiquer le mode de fonctionnement adapté pour manipuler des booléens ?

**Comment by laem** [comment]
@mquandalle @johangirod je vous ping ici car je ne suis pas sûr que vous suiviez ce repo, le site https://publi.codes étant déployé et discuté depuis betagouv/mon-entreprise

**Comment by laem** [comment]
Peut-être faut-il mettre un lien sur ce dépôt pour créer une issue sur mon-entreprise avec le label `moteur` ou `publicodes`, qu'en pensez-vous ?
