### ISSUE TITLE
Supprimer le mécanisme 'une possibilité'

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#10]
Aujourd'hui, le moteur permet de définir une formule avec le mécanisme 'une possibilité. La valeur de cette dernière est alors de type 'string'. 
```yaml
contrat salarié: 
  formule: 
    une possibilité:
      - CDD
      - CDI
      - stage
```

Cela permet ensuite d'effectuer des comparaisons entre les différentes possibilités. 

```yaml
applicable si: contrat salarié = 'CDD'
```
L'utilisation de ce mécanisme abouti également à un type de question particulier dans l'UI :
![Screenshot_2020-04-06 Mon-entreprise fr L'assistant officiel du créateur d'entreprise](https://user-images.githubusercontent.com/1775934/78581434-2c97cd80-7834-11ea-84e5-a9442d1442c5.png)

Bien qu'il soit pratique, ce mécanisme souffre de plusieurs limites conceptuelles.

### Un mécanisme qui n'en est pas un
Le but d'un mécanisme est de calculer une valeur à partir d'autres règles. En ce sens, il sont assimilables à des appels de fonctions. Ici, le but du mécanisme est tout autre : il définie les  valeurs possibles pour cette règle. En ce sens, il s'agit plus d'une information qui a attrait au **type** de la règle plutôt qu'à sa valeur. Il est par exemple impossible de faire appel au mécanisme 'une possibilité' depuis un autre mécanisme.

### Un type string pas vraiment pertinent
Le type string est uniquement utilisé pour des comparaisons de valeur de règles avec le mécanisme une possibilité, ainsi que pour l'affectation d'une valeur à une règle

Je propose de discuter ici de son évolution.

**Comment by mquandalle** [comment]
Discuté aujourd'hui : 
- Le mécanisme "une possibilité" n'est pas un vrai type union mais une simple liste de valeurs. 
- Supprimons le du langage
- Documentons pour les utilisateurs la manière de créer des questions à choix multiples via un "attribut" "possibilités" qui indépendant du moteur publicodes, dans https://publi.codes/docs/guides/cr%C3%A9er-formulaire
