### ISSUE TITLE
Type chaîne de caractère : possibilité d'échapper le guillemet simple

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#106]
Publicodes supporte un type chaîne de caractère `x = 'ma chaîne'`

Ce type est utile pour interfacer des données de l’extérieur. Par exemple sur mesaidesvelo.fr, je l'utilise avec des conditions sur l'appartenance d’une commune à un EPCI (intercommunalité), par exemple:

```yaml
aides . epinal:
  applicable si: localisation . epci = 'CA d'Epinal'
```

La chaîne de caractère `CA d'Epinal` est standardisée (il y a un gros excel avec la liste précise des EPCI), et j'aimerais pouvoir utiliser cette chaîne directement dans publicodes. En Javascript j'ai l'option soit d'utiliser des guillemets doubles, soit d’échapper le guillemet simple avec `\'`, mais publicodes ne permet aucune de ces deux possibilités.

C'est pas très gênant car ça se contourne facilement (en l’occurrence en modifiant l'entrée pour remplacer les guillemets simples par un autre caractère) mais pour un utilisateur tiers de publicodes c'est un fonctionnement buggé, on s'attend à pouvoir échapper un guillemet comme dans la grande majorité des langages.

**Comment by mquandalle** [comment]
(Il faut modifier la grammaire ici : 

https://github.com/betagouv/publicodes/blob/663ee8d687ce359c3cde4cfea2c7ba2f40fb47d1/packages/core/source/grammar.ne#L35
)

**Comment by wiinxt** [comment]
Est-ce que tu pourrais me passer un exemple qui ne fonctionne pas car j'ai fait plusieurs test et ça à l'air de fonctionner avec les escape yaml de base (double `'` ou combinaison de `"` et de `'`)
J'ai fait cet exemple avec plusieurs cas :
https://publi.codes/studio/localisation/epci?code=%0Alocalisation%3A%0Alocalisation+.+epci%3A+%27%27%27CA+d%27%27E%22pinal%27%27%27%0Alocalisation+.+epci2%3A+%22%27CA+d%27E%5C%22pinal%27%22%0A%0Aaides%3A%0Aaides+.+epinal%3A%0A++applicable+si%3A+localisation+.+epci+%3D+%27CA+d%27E%22pinal%27%0A++valeur%3A+%22%27te%27x%5C%22te%27%22%0A%0Aaides+.+epinal2%3A%0A++applicable+si%3A+localisation+.+epci2+%3D+%27CA+d%27E%22pinal%27%0A++valeur%3A+%27%27%27%22te%27%27xte%22%27%27%27%0A%0Atest%3A%0A++applicable+si%3A%0A++++toutes+ces+conditions%3A%0A++++++-+aides+.+epinal%0A++++++-+aides+.+epinal2%0A++valeur%3A+%3E%0A++++%27plop%0A++++test%3A+%27%0A++++test2%3A+%22%0A++++%5C%22a%22b%22c+%0A++++%5C%27a%27b%27c+%0A++++%27%0A%0Atest+.+texte%3A%0A++texte%3A+%3E%0A++++plop%0A++++test%3A+%27%0A++++test2%3A+%22%0A++++%5C%22a%22b%22c+%0A++++%5C%27a%27b%27c+%0A%0A

On pourrait peut être ajouter les `"` dans grammar pour les string (`string: [/'.*'/, /".*"/],`) ce qui nous permettrait de faire `valeur: '"te''x"te"'`

**Comment by wiinxt** [comment]
J'ai ajouté les double quote pour les string : https://github.com/betagouv/publicodes/pull/220

**Comment by mquandalle** [comment]
Implémenté dans #220
