### ISSUE TITLE
Corrections sur le nouveau site publicodes

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#114]
Suite à la mise en ligne du nouveau site publicodes dans #59, il y a un certain nombre de problèmes à corriger :

- sur le studio, l'URL n'est pas mise à jour lorsqu'on change la règle sélectionnée dans le volet documentation #193 
- la page `/mécanismes` s'affiche mal, j'ai posé une question à ce propos sur https://github.com/facebook/docusaurus/discussions/6009
- Revoir la coloration syntaxique utilisée pour le Yamll, j'ai essayé tous les [styles fournis par défaut](https://docusaurus.io/fr/docs/markdown-features/code-blocks) dans le thème Prism, mais aucun ne convient vraiment, il faudrait en trouver un autre et l'importer #194 

Il y a bien sûr de nombreuses autres évolutions à apporter à ce site, mais ces points sont des régressions directes par rapport à l'ancienne version.

**Comment by johangirod** [comment]
Par ailleurs, en bug un peu critique, la redirection depuis les pages de doc mon-entreprise vers le bac à sable publicode est cassée

https://mon-entreprise.fr/documentation/contrat-salari%C3%A9/r%C3%A9mun%C3%A9ration/net

**Comment by laem** [comment]
J'ajoute que sur la page des mécanismes, on n'a plus d'exemples de ces mécanismes. Je crois qu'ils y figuraient avant. Ils sont dispo dans https://github.com/betagouv/publicodes/blob/master/packages/react-ui/source/data/mecanisms.json.

**Comment by mquandalle** [comment]
Je ferme en faveur de #193 et #194, les autres problèmes remontés dans ce ticket ayant été résolus.
