### ISSUE TITLE
Séparer l'action de publication sur NPM

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#122]
Comme indiqué dans [ce commentaire](https://github.com/betagouv/publicodes/blob/9b70c758a3a647543049db2894d0e8a140308741/.github/workflows/test-publish.yaml#L56-L58), les actions seraient mieux organisées si le workflow de test et celui de publication étaient séparés.

La raison pour laquelle je ne l'avais pas fait était qu'en mettant la publication dans un workflow séparé, cela rendait difficile la récupération du message du commit `📦 Publicodes v1.0.0-beta.<n>` qui est utilisé par l'action.

Mais je réalise en fait que l'action [npm-publish](https://github.com/JS-DevTools/npm-publish) ne publie le paquet sur NPM que si elle détecte un changement de version par rapport à ce qui est publié sur NPM, donc on peut sans doute supprimer notre condition sur le message du commit ? cc @johangirod si jamais tu as un avis.

Par ailleurs, notre action se base sur un `npm publish` alors que c'est `yarn` qui est utilisé dans le dépôt. J'ai cherché des actions `yarn publish` mais je n'ai pas trouvé grand chose de convaincant, peut-être que le plus simple serait de repasser sur `npm` pour ce dépôt, confer aussi la discussion côté mon-entreprise https://github.com/betagouv/mon-entreprise/issues/1173

**Comment by johangirod** [comment]
Effectivement, la condition sur le message est de trop, mais j'ajouterai quand même une validation supplémentaire. Peut-être via un workflow dispatch ? 

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch

Pour le côté npm, ok pour passer en npm ce repo, je pense qu'il y aura aucun problème.

**Comment by mquandalle** [comment]
Ok par exemple ajouter un test du type :

```js
// Ensure all packages are always in sync
const publicodesVersion = import("packages/core/packages.json").version
const publicodesReactVersion = import("packages/react-ui/packages.json").version
expect(publicodesVersion === publicodesReactVersion)

// Ensure used versions are always referenced in the Changelog
const changelogContent = import('changelog.md')
expect(changelogContent.includes(`## ${publicodesVersion}`))
```

**Comment by johangirod** [comment]
Yep, c'est parfait.

**Comment by mquandalle** [comment]
Restons sur yarn pour l'instant, j'ai testé une migration vers `npm` dans la branche [npm](https://github.com/betagouv/publicodes/tree/npm). Rien de particulier, mais il faut changer un peu tous les scripts et certaines versions de paquets pour un bénéfice qui n'est pas si évident (au moins pour les développeurs actuels qui sont habitués à yarn).
