### ISSUE TITLE
Supprimer la librairie yaml du runtime publicodes

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#124]
Sur mon-entreprise, la conversion de yaml en json se fait à la compilation, et on n'a donc pas besoin d'avoir ce compilateur côté client. Il faudrait que ça soit une dépendance optionnelle du paquet `publicodes`, mais à voir si ça ne complique pas les tutos de prise en main.

**Comment by laem** [comment]
Je déterre cette issue, étant actuellement en train d'optimiser mes bundles (futur.eco et nosgestesclimat.fr). 
Le parser yaml, même dans sa v2 toute fraîche, semble un gros bloc facile à éliminer. 
Ça ne devrait pas être compliqué de donner l'instruction pour que les webpack et compagnie éliminent un nouveau fichier de parsing en yaml pour les applis qui n'en ont pas besoin (et on conseillera évidemment aux applis web qui embarquent publicodes de transformer les règles en JSON avant; côté serveur par contre c'est très pratique). 

https://github.com/betagouv/publicodes/blob/master/packages/core/source/parsePublicodes.ts#L40

**Comment by laem** [comment]
Si je pige bien, il faut marquer le package.json avec un "sideEffects": false, et séparer le parsing du YAML dans un autre fichier qui serait alors tree-shaké. 
Par contre, je ne vois pas comment on pourrait le faire sans changement cassant, ou sans pirouette pas très propre, le choix JSON/YAML étant fait aujourd'hui non explicitement par un appel de fonctions différentes, mais par un switch sur le type de l'argument de parsePublicodes. 

Du coup quitte à faire un changement cassant, pourquoi ne pas laisser l'utilisateur choisir sa lib de parsing yaml préférée et passer du JSON à publicodes ? Je ne vois pas d'intérêt à embarquer la lib YAML dans le paquet finalement. 

Qu'en pensez-vous @johangirod @mquandalle ?

**Comment by johangirod** [comment]
En y réfléchissant, on peut faire le constat suivant : le format "Objet JavaScript" accepté en entrée du moteur est une représentation intermédiaire (cf #36). 

Pour l'instant, la représentation initiale suit la syntaxe du `yaml`, on utilise donc le parseur yaml pour passer du fichier publicodes en cette représentation intermédiaire "objet JavaScript". 

Rien n'empêche que l'on fasse évoluer la syntaxe du langage si on le souhaite dans le futur : il n'y aura qu'à changer cette logique qui passe de publicodes "texte" en du publicodes représenté sous forme d'objet JavaScript.

Par conséquent, on peut effectuer les changements suivants : 

1. Supprimer la dépendance yaml de l'Engine de base dans `core`
2. Créer une classe `YamlEngine`  (pas sûr du nom) qui étend `Engine`qui peut opérer sur du yaml, en effectuant le parsing yaml des règles à l'initialisation (et même potentiellement à l'évaluation `evaluate` ou au `setSituation`).
3. Choisir si l'on souhaite exporter par défaut le `YamlEngine` ou `Engine` (potentielle breaking dans un cas). Je serai d'avis d'exporter le YamlEngine par défaut (et de renommer l'autre ObjectEngine par exemple).

**Comment by mquandalle** [comment]
D'accord aussi sur l'intérêt de clarifier un format de représentation intermédiaire en Json qu'il faudra aussi documenter.

Sur l'API je pense qu'on peut forcer un modèle du type

```ts
type OurYamlLang = string
type IntermediateRepresentation = Object

function parse(source: OurYamlLang): IntermediateRepresentation
class Engine { constructor(source: IntermediateRepresentation) }


// utilisation
new Engine(parse(rawString)) // parse(rawString) n'a pas besoin d'être fait côté client et peut être fait lors du build
```

Autrement dit imposer d'appeler `parse` et ne plus accepter `new Engine(textSource)`


Je me pose un peu la question du format `IntermediateRepresentation`. Actuellement on manipule deux formats d'objets JSON : 
- un qui est la correspondante direct du yaml `{somme: ['a', 'b']}`
- un “AST” du type `{nodeKind: "somme", operands: [{ nodeKind: "reference", resolvedName: "xxx . a" }, { nodeKind: "reference", resolvedName: "yyy . b" }]}`

Une possibilité qui me titille s'est d'accepter uniquement le deuxième format. Vu que ça n'est pas du tout pratique à écrire à la main, il faudrait des fonctions utilitaires correspondants aux mécanismes pour générer cet objet : 

```js
import { somme, ref } 'publicodes/mecanims'

engine.evaluate(somme([ref('xxx .a'), ref('yyy . b')]))
```

Ça revient un peut au même mais il me semble que ça pourrait permettre à des utilisateurs tiers de définir leurs propres mécanismes sans passer par une API type `engine.registerMechanism`, et potentiellement avoir une correspondance publicodes ←→ Javascript plus poussée.

Ceci dit ce n'est sans doute pas trivial à implémenter donc `engine.evaluate({ somme: ['a', 'b'] })` peut être un bon format intermédiaire à utiliser et documenter
