### ISSUE TITLE
Add more integration examples

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#131]
Our repository currently host a single example of an app using publicodes — made with create-react-app. I would be great to provide examples for other environments (and add them to our CI) to ensure publicodes works everywhere.

For instance Next.js provide a wide range of examples : https://github.com/vercel/next.js/tree/canary/examples and they even have a page on their site listing all the examples, which is better for some users than navigating on Github : https://nextjs.org/examples

We don't need as many example as Next.js but we could have something like : 

```
examples/
  customize-documentation-style/
  with-create-react-app/
  with-svelte-kit/
  with-deno/
```

**Comment by laem** [comment]
I'll soon provide another simple React exemple :)

**Comment by mquandalle** [comment]
Related : #62 — we should make these examples clonable in a single command line

**Comment by johangirod** [comment]
NextJS example is done, as well as svelte kit in documentation. The other ones should be added when requested.
