### ISSUE TITLE
Units: mois/an & points/point… don't simplify automatically

### ISSUE THREAD

**Issue by lajarre** [betagouv/publicodes#144]
Repro case:

```js
const myRules = `euros: 1 €
points: 5 points
point: 5 point
mois: 24 mois
an: 2 an`

const myEngine = new Engine(myRules)

// Returns a nodeValue of 12 instead of 1, and a complex unit like €.points.mois/point.an
myEngine.evaluate('euros * points / point * mois / an')
```

Same goes with the following:

```js
engine.evaluate({valeur: 'euros * points / point * mois / an', unité: '€'})
```

By the way, in the last case, it seems "unité" is not validated for correctness against the inferred unit).

We would expect both evaluations above to yield a `nodeValue` of `1` and a unit of `€`.

**Comment by mquandalle** [comment]
Seems fixed 

https://publi.codes/studio/bug?code=euros%3A+1+%E2%82%AC%0Apoints%3A+5+point%0Apoint%3A+5+point%0Amois%3A+24+mois%0Aan%3A+2+an%0A%0Abug%3A+euros+*+points+%2F+point+*+mois+%2F+an
