### ISSUE TITLE
Nouveau mécanisme pour la mise en forme de texte

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#152]
### Besoin identifié

Certains utilisateurs de `publicodes` évaluent la clé `question` des règles comme une formule publicodes. Cela leur permet d'afficher un texte différent en fonction de la situation, via l'utilisation du mécanisme `variation`. C'est le cas de [mes aides vélo](https://github.com/mquandalle/mesaidesvelo/blob/master/src/aides.yaml#L2688-L2695) ou du [formulaire mobilité dans mon-entreprise](https://github.com/betagouv/mon-entreprise/blob/master/site/source/pages/Gerer/DemandeMobilite/demande-mobilit%C3%A9.yaml#L635-L640).

Je compte utiliser la même technique pour le formulaire d'exonération covid 2021, mais j'arrive à la limite de ce qui peut être fait via le mécanisme variations. Je dois ainsi afficher la question suivante : 
> Précisez le nombre de mois entre <[février] 2021 (à remplacer pas le mois de début d’activité si celui-ci est à compter de mars 2021)> et <juillet 2021 ou septembre si outre-mer> durant lesquels vous avez fait l’objet d’une mesure d’interdiction affectant de manière prépondérante la poursuite de votre activité

Il y a trop de cas à traiter pour utiliser une variation (2 × 7 = 14 cas minimums).

### Solution : nouveau mécanisme de templating : `texte`

Je propose un nouveau mécanisme de templating pour mettre en forme des chaînes de charactère. Ce dernier prendrait un texte avec les valeurs à interpoler entre des blocs `{{ }}` (plutôt classique en templating).

Exemple : 

```yaml
 question:
    texte: |
      Précisez le nombre de mois entre {{ premier mois }} et {{ dernier mois }} durant lesquels 
      vous avez fait l’objet d’une mesure d’interdiction affectant de manière prépondérante la poursuite 
      de votre activité
``` 

Les expressions entre `{{ }}` étant évaluée comme du publicodes. On pourra être tenté d'ajouter une possibilité de mise en forme des types de base par la suite (nombre, date, booléen) par la suite. Cela sera relativement direct, mais il s'agit d'une fonctionnalité séparée, indépendante de celle-ci.  

Note : cette solution avait été déjà été discutée ici : https://github.com/betagouv/publicodes/issues/121

### Prochaines étapes

Étant donné la simplicité de la spécification, je pense passer dès maintenant à une proposition d'implémentation (s'il n'y a pas d'oppositions).

**Comment by mquandalle** [comment]
Note: J'ai eu ce besoin aussi, je suis passé par un format ad-hoc : https://github.com/mquandalle/mesaidesvelo/blob/fbc1fd747fb81fbfe459c54fe116c6d6354bc973/src/aides.yaml#L75

Ici les chaînes `$vélo` et `$plafond` sont remplacées par l'évaluation d'une règle texte. La solution `{{ }}` me semble bien préférable, y compris pour le sujet d'interpolation des traduction dont on discutait dans #120.

**Comment by mquandalle** [comment]
Techniquement l'implémentation est faisable côté mon-entreprise non ? Je suis super favorable à l'intégrer dans le moteur, c'est juste probablement plus facile à développer avec l'UI du formulaire covid en parallèle ?

**Comment by johangirod** [comment]
Vu que la fonctionnalité est bien spécifié je pense que je peux la développer en TDD côté publicodes, si tu n'y vois pas d'inconvénient

**Comment by mquandalle** [comment]
Je suis tenté de supporter l'interpolation sur toutes les chaînes de caractères sans avoir à les envelopper dans un mécanisme `texte`

**Comment by johangirod** [comment]
> Je suis tenté de supporter l'interpolation sur toutes les chaînes de caractères sans avoir à les envelopper dans un mécanisme texte

Ah oui, ça pourrait le faire aussi.

Je garderais tout de même le mécanisme texte qui permet d'écrire une chaîne de caractère sur plusieurs lignes / sans avoir à l'entourer de `"'<string>'"`

L'inconvénient d'interpoler par défaut serait principalement au niveau des perfs : obligation de parser toutes les chaînes de caractère pour détecter s'il y a des `{{ }}` dedans.
