### ISSUE TITLE
Ajoute un test pour vérifier que le bac à sable utilise la dernière version de publicodes

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#165]
Une github action qui vérifie que `website/package.json` est mis à jour à chaque changement de version.

**Comment by mquandalle** [comment]
Maintenant que `website` et `publicodes` sont 2 workspaces du même “groupe” c'est toujours la version locale de publicodes qui est utilisé pour le site (et donc `master` sur https://publi.codes). C'est très pratique en dev et ça ne me semble pas gênant tant qu'on publie rapidement nos gros changements sur NPM après le merge sur `master`.
