### ISSUE TITLE
missingVariable : comportement inattendu depuis la refacto applicabilité

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#178]
### Situation 
```yaml
a: 
  somme: 
    - nom: b
    - nom: c
```

```ts
engine.evaluate('a . b').missingVariables // { 'a . b' : 1 } ✅
```

```yaml
a: 
  applicable si: oui
  somme: 
    - nom: b
    - nom: c
```

```ts
engine.evaluate('a . b').missingVariables // { 'a . b' : 1,  'a . c' : 1 } ❌
```

### Attendu

On s'attends à ce que les missings variables de `a . b` ne contiennent pas celles de la somme du parent, mais uniquement celles qui conditionnent son applicabilité.

Il est possible que l'on ne fasse pas l'économie d'un type d'évaluation distinct pour l'applicabilité (`evaluateApplicability`). À réflechir...

**Comment by johangirod** [comment]
Par ailleurs, un autre comportement qui est inattendu : 

```yaml
a:
a . x: 3
```

```yaml
a:
a . x: 3
b: 
  valeur: non
  rend non applicable: a
```

`a` est remonté comme `missingVariables` de `a . x` dans le deuxième cas, alors qu'il ne l'était pas dans le premier. Autrement dit, il y a un effet de bord.

[Voir l'exemple dans le studio](https://publi.codes/studio?code=%0Aa%3A%0Aa+.+x%3A+3%0A%0Ab%3A+%0A++valeur%3A+non%0A++rend+non+applicable%3A+a)

**Comment by mquandalle** [comment]
Merci pour les exemples ! L'implémentation de l'applicabilité n'est donc toujours pas la bonne, c'est vraiment pas évident comme problème !

Ces deux exemples suggèrent effectivement qu'on a besoin d'une fonction `evaluateApplicability` distincte de `evaluate`.

L'implémentation précédente fonctionnait pour ces cas, en quickfix on peut donc la restaurer.

Son design n'était cependant pas génial : limité à un mécanisme (somme) et implémenté sous la forme d'état global modifié. Par ailleurs elle créait 2 caches distincts sans détecter que certaines nœuds avait la même valeur dans le calcul de l'applicabilité que dans l’évaluation de la `nodeValue` (donc certains calculs sont réalisés une deuxième fois inutilement).

Je vois l'évaluation de l'applicabilité comme une forme d'évaluation partielle, c'est à dire que dans

```yaml
a:
  applicable si: x
  somme:
    - b
```

Pour savoir si `a` est applicable on veut calculer la ligne `applicable si: x` mais pas la somme en dessous. Le problème c'est que l'implémentation des mécanismes chaînés rend difficile de s'arrêter à la première ligne car dans l'AST le mécanisme `somme` est à intérieur du mécanisme `applicable si`, et lors de l'évaluation c'est ce dernier que se charge de la “continuation” (lancer le calcul de `somme` si la condition d'applicabilité est respectée).

```js
const ast = {
  nodeKind: 'applicable si'
  explanations: {
    condition: { ... }
    valeur: { nodeKind: 'somme', ... }
  }
}
```

Une alternative serait d'avoir un AST sous forme de liste ordonnée (sans imbrication des mécanismes lors du parse), et avoir une fonction lors de l'évaluation du type `evaluateChainedMechanisms` qui évalue les mécanismes dans l'ordre et puisse s'arrêter quand c'est nécessaire :
- si on calcule juste l'applicabilité on s'arrête après `applicable si` / `non applicable si` (ou éventuellement on regarde le typage statique des nœuds et on s'arrête quand le reste de la liste n'est plus “nullable”)
- si on calcule la valeur du nœud on calcule tout (sauf si le mécanisme précédent retourne `null` ou `undefined`.

L'avantage que je vois à cette implémentation c'est de garder un cache unique entre l'évaluation des valeurs et celle de l'applicabilité — cette dernière devenant une forme d'évaluation partielle.

Ça demande encore a être creusé ceci dit. Le plus simple pour corriger ces 2 problèmes rapidement peut être d'ajouter tes deux exemples dans les tests unitaires de publicodes et de ré-introduire la logique implémentée dans #66 (et supprimée dans #159)
