### ISSUE TITLE
Régression dans la version v1.0.0.beta-31

### ISSUE THREAD

**Issue by fmata** [betagouv/publicodes#187]
Bonjour,

Nous étions en version v1.0.0.beta-26, nous souhaitons mettre à jour en 32 (la 33 n'étant pas encore dispo sur npm, quand est-ce prévu ?). Or tous nos tests échouent depuis la version 31. A la lecture du changelog, rien indique un changement cassant nous concernant.

L'erreur est la suivante (nous utilisons quasi toutes les règles de modele-social de janvier 2022, y compris base.yaml, + des règles personnalisées) :
```
Error:
    [ Erreur syntaxique ]
    :arrow_right:  Dans la règle "année"
    :heavy_multiplication_x:  :arrow_right: Dans le mécanisme valeur
    (rawNode + "").replaceAll is not a function
```
Nous essayons en vain de trouver le commit qui a introduit la régression en buildant chaque commit entre la version 30 (80f038522b04fbdb9fc5ff099d4adbdc0e5cc31b ?) et 31 (9b104954a1e25ff2f780f5ba48d83ba635767534 ?) or c'est une tâche très difficile car aucune version n'est taguée dans le dépôt, donc on doit se fier aux commits qui mettent à jour CHANGELOG.md...

De plus, on a du mal à build manuellement pour utiliser les dists générés dans notre app. Fournir un dossier dist/ dans le dépôt serait bien plus pratique puisqu'on aurait qu'à faire un lien symbolique depuis notre dossier node_modules/publicodes/dist/.

Pouvez-vous nous aider svp ?

Merci

**Comment by mquandalle** [comment]
Bonjour @fmata, il s'agit d'une régression corrigée dans 9b0b892b194286cdc14b734847c1c6a7f01faad6. La version `beta-33` corrige ce bug, mais effectivement la publication automatique sur NPM a échoué, on va regarder pourquoi https://github.com/betagouv/publicodes/runs/5629281730?check_suite_focus=true

> De plus, on a du mal à build manuellement pour utiliser les dists générés dans notre app. Fournir un dossier dist/ dans le dépôt serait bien plus pratique puisqu'on aurait qu'à faire un lien symbolique depuis notre dossier node_modules/publicodes/dist/.

Pour faire un build manuel il faut exécuter la commande `cd packages/core && yarn build`, puis le code est dans le répertoire `dist/`.

**Comment by fmata** [comment]
Ok, avec node v16 cela fonctionne à nouveau. Est-ce que node v16 est supportée officiellement par publicodes ?

C'est éventuellement une façon de contourner le problème en attendant que la version 33 soit publiée bien que ça requiert des opérations sur nos infras.

**Comment by mquandalle** [comment]
Bonjour @fmata, le problème est corrigé dans la `beta-33` qui a été publiée sur NPM.

Concernant l'ajout de tags git c'est suivi sur #134.
