### ISSUE TITLE
Les mécanisme plancher et plafond ne fonctionne pas sur les dates

### ISSUE THREAD

**Issue by wiinxt** [betagouv/publicodes#188]
Dans cet exemple on a toujours `01/01/2021` comme valeur alors que ça devrait être `01/12/2020` avec le `plafond` ou `01/02/2021` pour le `plancher` :
https://publi.codes/studio?code=d%C3%A9duction+fiscale+1%3A%0A++valeur%3A+01%2F2021%0A++plancher%3A+02%2F2021%0A%0Ad%C3%A9duction+fiscale+2%3A%0A++valeur%3A+01%2F2021%0A++plafond%3A+12%2F2020

**Comment by mquandalle** [comment]
C'est corrigé 🎉
