### ISSUE TITLE
Réecriture des mécanismes avec un petit nombre de mécanisme de base

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#23]
Dans la lignée de ce qui a été discuté dans betagouv/publicodes#6 et un peu partout sur les différentes issues liées au la formalisation de publicode, je propose de définir un certains nombre de mécanisme "brique de base" avec lesquels tous les mécanismes "dérivés" serait réecrit. 

Je vois pour l'instant les mécanismes de base suivants : 
- Opération binaire (+, -, /, ×, <, >, =, ≤, ≥, !=, et, ou)
- Variation ternaire (`si a alors b sinon c`)
- Par défaut
- Unité
- Nom (affectation d'une valeur en tant que règle)

Tous les autres mécanisme doivent pouvoir être implémenté comme une réécriture d'une expression avec ces mécanismes de base, autrement dit, du sucre syntaxique. C'est déjà le cas de `composante` dans betagouv/mon-entreprise#1191.

Voici ce que cela donnerait les transformations statiques. Les réecritures sont en javascript. L'objet v correspond à l'objet yaml sous le nom du mécanisme

### Plafond
```js
`
variations:
 si: ${v.plafond} != non ET ${v.valeur} > ${v.plafond}
 alors:  ${v.plafond}
 sinon: ${v.valeur}
`
```

### Applicable si
```js
`
variations:
  si: ${v.condition} != non
  alors: ${v.valeur}
  sinon: non
`
```

### Produit
```js
`
operation ×:
   - valeur: ${v.assiette}
     plafond: ${v.plafond ?? 'non'}
   - operation ×:
       - ${taux ?? '100%'}
       - ${facteur ?? '1'}
`
```

### Somme
```js
v.reduce((somme, terme) => `
operation +:
  - ${terme}
  - ${somme}
`, '0')
```

### Variations 
```js
v.reduce((variations, terme ) => `
variation:
  si: ${terme.si}
  alors: ${terme.alors}
  sinon: ${variations}
`, 'non')
```

### Grille
```js
`
variations:
  ${v.tranches.map(t => `
  - si: ${v.assiette} × $[v.multiplicateur} <= ${t.plafond}
    alors: ${t.valeur}
`).join('\n')}
 
```

### Barème
```js
`
somme:
  ${v.tranches.map(t => `
  - produit:
      assiette: ${v.assiette}  - ${v.plancher}
      plafond: ${v.plancher} - ${v.plafond}
      taux: ${v.taux}
`).join('\n')}
```

...etc.

## Avantages 

L'utilisation d'un nombre limité de mécanisme de base a le gros avantage de réduire le périmètre du langage publicode "core". Cela veut dire limiter les implémentations de l'inférence de type et de l'évaluation (avec la logique des missings, ou des variables temporelles) a un petit nombre de mécanisme. 

Les gros mécanisme étant définis comme une combinaison de petit mécanisme, ils héritent des propriétés du langage sans que l'on ait à les réimplémenter. Cela permet d'être d'avantage rassuré quand à la validité de l'implémentation des gros mécanisme.

## Lien avec les fonctions

Ce principe de gros mécanisme vs petit ressemble au principe des fonctions dans n'importe quel langage. C'est effectivement l'idée. Les gros mécanisme étant en fait des fonctions définie avec des opérations de base. Si on ajoute pas directement cette abstraction dans publicodes, c'est pour deux raisons principales.

1. Cette proposition est une étape intermédiaire et demande donc moins de modifications que l'ajout des fonctions
2. Pour réecrire les mécanisme de barème et somme sous forme de fonction publicode, il faudrait ajouter l'abstraction des listes, qui n'existe pas encore

Mais il est encouragé de considérer les gros mécanisme comme une fonction.

## Considération sur les performance : 

On voit ici que cette réecriture peut être couteuse en terme de performance. Par exemple, la réecriture du mécanisme plafond : 
```js
`
variations:
 si: ${v.plafond} != non ET ${v.valeur} > ${v.plafond}
 alors:  ${v.plafond}
 sinon: ${v.valeur}
`
```
revient à évaluer l'expression `v.plafond` trois fois de suite. C'est beaucoup, surtout si c'est une expression compliquée, avec des inversions dedans par exemple. 

Je propose d'ajouter un nouveau mécanisme permettant de spécifier lorsque que des valeurs sont les même : cache. On aurait ici : 
```js
const plafond = `
valeur: ${plafond}
cache: ${new uuid()}
`;
const valeur = `
valeur: ${valeur}
cache: ${new uuid()}
`;
`
variations:
 si: ${plafond} != non ET ${valeur} > ${plafond}
 alors:  ${plafond}
 sinon: ${valeur}
`
```
Lors de l'évaluation ou lors de la vérification de type, c'est une valeur cachée qui serait utilisée.

## Mécanisme intermédiaires
Certains mécanismes ne peuvent pas être réecrit via des mécanismes de base sans pour autant en faire parti. C'est le cas de `inversion`, `recalcul` ou encore `synchronisation`

Il doivent être définit complètement (évaluation, inférence de type et missing variables), de la même manière que les mécanismes de base. Mais ils n'en font pas parti car on interdit leur utilisation pour l'écriture de gros mécanisme.

Pourquoi ? Principalement parce qu'il ne sont pas aussi 'solide' que ceux si. En attendant de comprendre mieux les enjeux formels qui leurs sont associés, je propose de les mettre de côté.

## Visualisations
Tous les mécanismes ont une visualisation spécifique. Les gros mécanisme peuvent ainsi "écraser" la visualisation de leur enfant en définissant une qui leur correspond mieux (et qui est plus simple à comprendre). C'est déjà le cas pour [`composantes`](https://github.com/betagouv/mon-entreprise/blob/refacto-evaluation-r%C3%A8gle/publicodes/source/mecanisms/composantes.ts#L24-L27) dans betagouv/mon-entreprise#1191 

## Questions et prochaines étapes
L'AST serait donc composé uniquement de mécanisme de base et intermédiaire. Mais il faudrait qu'il garde la trace des mécanismes avant la réecriture pour l'affichage.  Je ne sais pas encore quelle forme cela prendrait. Je pense que le mieux, c'est de commencer avec un mécanisme à réecrire (par exemple produit) et expérimenter un peu sur quelle implémentation marcherait bien. 

Qu'en pensez vous ? 

*Reliée à betagouv/mon-entreprise#1015*

**Comment by Knaizi** [comment]
Comparaison de deux tableaux en langage c

**Comment by mquandalle** [comment]
@johangirod fermé par #217  ?

**Comment by johangirod** [comment]
En partie. Il manque encore l'implémentation des mécanismes suivants : 
- Barème
- Grille
- TauxProgressif
- Variation

Mais je pense qu'il faudra attendre d'avoir un vrai type liste et peut-être même des fonctions native ?

En attendant, on peut fermer cette issue, et en rouvrir une autre plus restreinte sur ces mécanismes restants avec la problématique particulière des listes.
