### ISSUE TITLE
Ajouter des liens vers des articles parlant de publicodes sur le site web

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#233]
- https://ressourcerie.fabrique.social.gouv.fr/articles/publicode-art
- https://kont.me/l-état-nous-doit-des-explications
- https://pad.incubateur.net/umkhdmzES_SS5InXezin4Q#
- ...?

**Comment by revolunet** [comment]
https://socialgouv.github.io/demo-publicodes ?

**Comment by laem** [comment]
@revolunet le premier lien de Johan, publicode-art est down, c'était quoi ?

**Comment by revolunet** [comment]
en effet, c'était un article sur le site de la "ressourcerie" : https://github.com/SocialGouv/ressourcerie/blob/a29a84d921e7e9d6c1a549242333a59f82b4cfcf/_data/old/guides/publicode-art.md

mais qui a été dépublié pour une raison inconnue... je me renseigne

**Comment by laem** [comment]
@revolunet j'ai mis mon article dans une nouvelle section "pourquoi publicodes" sur cette PR #338 . 

Ton lien "démo publicodes" pourrait aller dans "Guides>Démos de simulateurs" ?
