### ISSUE TITLE
Les liens vers les ancres ne sont pas font pas défiler la page 

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#236]
Lorsqu'on fait un lien vers un mécanisme (exemple depuis la page documentation), la page n'est pas défilée.

https://user-images.githubusercontent.com/1775934/171582233-3530ed4b-b2a8-4645-8d76-42c64a1d054e.mp4

-> https://publi.codes/docs/m%C3%A9canismes/#somme

**Comment by mquandalle** [comment]
C'est corrigé sur la version en ligne https://publi.codes/docs/m%C3%A9canismes/#somme
