### ISSUE TITLE
Performances très dégradées pour les mécanismes `le maximum de` et `le minimum de`

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#237]
La refacto #217 a entraîné une forte dégradation des performances pour la manipulation interne des listes, confer https://github.com/betagouv/publicodes/pull/217#discussion_r878511119

Exemple de calcul qui pose problème (fait tourner mon ventilateur à fond, gel du navigateur) :

```yaml
example:
  le maximum de:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
```

[studio](https://publi.codes/studio/example?code=example%3A%0A++le+maximum+de%3A%0A++++-+1%0A++++-+1%0A++++-+1%0A++++-+1%0A++++-+1%0A++++-+1%0A++++-+1%0A++++-+1%0A++++-+1)

Connexe #26. Mais il est peut-être possible de trouver un correctif rapide / hacky uniquement pour résoudre ce problème de performance sans forcément résoudre le problème plus général du type liste.

**Comment by johangirod** [comment]
Ah oui il y a clairement un problème quelque part... On dirait qu'il y a une complexité exponentielle. Ceci étant dit cela a l'air d'être circonscrit aux mécanismes maximum / minimum (pas le cas pour somme / toutes ces conditions / une de ces conditions). 

Je peux renommer l'issue en ce sens ?
