### ISSUE TITLE
Cacher les notions techniques sur la documentation

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#241]
Sur la capture ci-dessous il faut cacher les informations techniques qui ne sont compréhensibles que pour des développeurs publicodes :
- lien vers le bac à sable
- données manquantes
- règles enfants 

![Capture d’écran du 2022-07-02 10-31-02](https://user-images.githubusercontent.com/1730702/176390582-420b9111-a060-4cfd-87dd-e57bb5829e78.png)

**Comment by laem** [comment]
@mquandalle ça me semble être fait, je ferme
