### ISSUE TITLE
Choix multiples chiffré

### ISSUE THREAD

**Issue by laem** [betagouv/publicodes#25]
Sur nosgestesclimat, on a une question sur l'alimentation pour laquelle j'ai codé un composant de saisie personnalisé.

![Screenshot_20201207-105508_Kiwi Browser](https://user-images.githubusercontent.com/1177762/101336427-bf34b480-387a-11eb-9c9b-e9a69aa33b78.jpg)

Concrètement, le composant va renseigner pour chaque plat d'une somme de 4 plats, une variable de second niveau `nombre`, avec une contrainte somme des nombres = 14 (14 midis et diners par semaine).

C'est un besoin qu'on a plusieurs endroits, notamment sur la question aviation.

![Screenshot_20201207-105446_Kiwi Browser](https://user-images.githubusercontent.com/1177762/101336614-f905bb00-387a-11eb-9f28-44e4cb9e1e7b.jpg)

On pourrait l'implémenter comme un bloc suggestions plus évolué : quand on clique sur "Paris->Le Caire", on ajoute une valeur à l'Input, on peut an ajouter une deuxième etc. L'utilisateur voit la somme en bas, et peut aussi l'écraser s'il veut faire le calcul lui-même.

**Comment by laem** [comment]
Finalement, cette issue est bien un sujet relativement différent des listes. 
Les listes permettent de créer un nombre infini d'entrées, qu'il faut ensuite sommer. 

La mosaïque est définie dans le modèle, et le nombre de saisies est alors fixe. 

L'issue de cette discussion serait probablement qu'il faut documenter le composant mosaïque, en l'absence d'une bibliothèque publicodes-questions.

**Comment by laem** [comment]
Le type liste, et surtout le type "somme de tous les objets de tel type" pourrait bien sûr aider à faciliter l'écriture dans le modèle de ce genre de situations, mais il y a des chances qu'on continue à définir les variables "repas 1", "repas 2" de façon classique dans le code.

**Comment by mquandalle** [comment]
@laem vous avez bien avancé sur les composants de saisie côté nosgestesclimat, faut-il ré-ouvrir des issues plus spécifiques sur ce qu'il faut intégrer dans le moteur ?

**Comment by laem** [comment]
Oui, je pense qu'on peut fermer ce sujet, qui restera là comme référence.
