### ISSUE TITLE
Site web : Lien vers la liste des mécanismes invalide

### ISSUE THREAD

**Issue by sashabcd** [betagouv/publicodes#255]
Bonjour,

Sur la page [Principes de base](https://publi.codes/docs/principes-de-base/#m%C3%A9canismes-cha%C3%AEn%C3%A9s) le lien « Voir la liste des mécanismes existants » semble invalide. 

Probablement en rapport avec :  
https://github.com/betagouv/publicodes/blob/b930cfbddbbc4f6d99a0f5fc0fdc1303e843c865/website/docs/principes-de-base.mdx?plain=1#L159

**Comment by revolunet** [comment]
a priori ca a été fixé ici : https://github.com/betagouv/publicodes/pull/279
