### ISSUE TITLE
Supprimer le mécanisme synchronisation

### ISSUE THREAD

**Issue by wiinxt** [betagouv/publicodes#258]
Ce mécanisme n'est utilisé que pour `établissement . localisation`  ([voir code](https://github.com/betagouv/mon-entreprise/blob/28ddd61d8de482f5ac60c9aa6c819f978f626913/modele-social/r%C3%A8gles/entreprise/base.yaml#L665-L706)) et n'a pas d'avantage par rapport à des règles normal, Publicodes ne gérant pas lui même les requêtes api.

Johan à regardé dans d'autre base de code et n'a pas trouvé d'autre utilisation de ce mécanisme.

**Comment by laem** [comment]
C'était en effet plutôt spécifique comme mécanisme :)
