### ISSUE TITLE
Comportement anormal conditions d'applicabilité

### ISSUE THREAD

**Issue by Clemog** [betagouv/publicodes#259]
Hello ! 

- Petit retour d'un comportement non attendu sur Nos Gestes Climat au niveau de l'applicabilité d'une question :
Avant cette [modif](https://github.com/datagir/nosgestesclimat/commit/ea40a28caf41d5d130d78435ddca83e9250d33e7), la question "Quel type de deux roues thermique utilisez-vous ?"  arrivait avant "Utilisez-vous un scooter ou une moto ?" alors qu'auparavant 
Je ne sais pas très bien de quand date ce bug.

- Deuxième retour : au niveau de la [cette PR](https://github.com/datagir/nosgestesclimat/pull/1433), je fais appel à une variable dans la définition de la valeur par défaut mais la question dont dépend cette condition est posée après. https://github.com/datagir/nosgestesclimat/blob/f81b789bed2763c8176bb8abc621bf86d3a0e1af/data/logement/logement.yaml#L158-L166

**Comment by johangirod** [comment]
Salut ! J'ai corrigé des petits bugs au niveau des missingVariables dans la dernière PR #252
Ceci étant dit nous n'avons pas encore fait de mise à jour de version avec les modifications. Tu peux tester en local en linkant les paquets pour voir si ces problèmes sont corrigés sur master. On va faire un upgrade de version sous peu sinon.

**Comment by Clemog** [comment]
J'ai testé avec un `yard build` dans `package/core` et en l'important directement dans le dépôt mais j'ai l'impression que les 2 erreurs persistent

**Comment by johangirod** [comment]
Ah, mince, c'est dommage. Penses-tu pouvoir réussir à reproduire le bug dans un cadre plus unitaire ? Afin que l'on puisse regarder de plus près ?

**Comment by Clemog** [comment]
J'essaie d'investiguer yes :)

**Comment by johangirod** [comment]
Merci pour ces précisions, c'est beaucoup plus clair. Il y a effectivement un ajustement à faire pour ces deux cas. Le premier à l'air d'être un bug. Ceci étant dit ce n'est pas forcément une bonne pratique de conditionner l'applicabilité d'un espace de nom à une sous-question.

En effet, si tu souhaitais mettre une valeur par défaut à usager à `non`, dans l'état actuel des choses, l'espace de nom deviendrait non applicable... ce qui aurait pour conséquence de transformer usager en `non applicable` également. On préfère dans `mon-entreprise` déplacer la condition d'applicabilité au même niveau que l'espace de nom et avoir la valeur dans une règle enfant (`montant` ou `émission` par exemple dans votre cas).

On a une piste pour répondre à ce problème : changer l'implémentation de la désactivation de branche pour rejoindre celle des remplacements. Désactiver une branche reviendrait à rendre non applicable toutes les références **extérieures** vers les règles de cette branche (cf #206)

Concernant le second cas, c'est actuellement une fonctionnalité plutôt qu'un bug. En effet, la sémantique du `par défaut` correspond au bouton « je ne sais pas ». L'idée est de poser d'abord la question de la valeur à calculer en priorité, et si c'est une donnée inconnue de l'usager, alors de poser des questions supplémentaires pour l'aider à la retrouver. 

Dans ton exemple, poser la question du chauffage à l'électricité n'a pas d'intérêt si l'utilisateur connait par cœur le montant de la facture. Sauf si vous l' utilisez ailleurs, et dans ce cas, vous pouvez en faire un objectif de la simulation, ce qui remontera son poids.

**Comment by Clemog** [comment]
La question du chauffage fait partie d'une mosaique avec plusieurs types de chauffages au choix et la variable chauffage . électricité . chauffage est effectivement nécessaire ailleurs (notamment au niveau des actions) donc effectivement c'est un cas particulier qui n'est pas un bug ! 
merci pour les retours !
