### ISSUE TITLE
Warnings ignored in the studio

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#293]
Example : https://publi.codes/studio/courses?code=courses%3A%0A++somme%3A%0A++++-+2+choux%0A++++-+5+carottes%0A

I believe it used to work and the code the collect the warning is already there.

cc @revolunet

**Comment by mquandalle** [comment]
Weirdly this work in the studio in dev mode

![image](https://user-images.githubusercontent.com/1730702/203861630-7f949c68-5a5b-4837-bf9e-553a7ff0bfff.png)

**Comment by johangirod** [comment]
Fixed now.
