### ISSUE TITLE
Implement unit pluralization

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#294]
It should be possible to use multiple variants of the same unit in a publicodes file, example : 

```yaml
duration: 1 day + 3 days
```

If it's not broken it's already possible to do it using the [`getUnitKey`](https://github.com/betagouv/publicodes/blob/master/packages/core/source/units.ts#L9) option when instantiating the engine. We need to 

- add unit  tests
- document this parameter

Or maybe `getUnitKey` isn't the best solution and we want to define these unit correspondances directly in the publicodes file as proposed in #199

**Comment by johangirod** [comment]
We use the discussion to think on this feature.
