### ISSUE TITLE
WIP Déplacer Publicodes dans son propre dépôt GitHub

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#32]
Initialement entremêlés, les codes sources de mon-entreprise et de publicodes sont maintenant bien séparés. Mais il reste à déplacer le code source et les tickets de publicodes dans un dépôt GitHub dédié, très probablement https://github.com/betagouv/publicodes.

Pour les développeurs de mon-entreprise, il restera utile de faire évoluer le moteur et le site dans le même temps en limitant les frictions de coordination suite à l'autonomisation des 2 projets, afin par exemple de pouvoir tester une évolution d'API sur notre base de code réelle (#1312).

Je n'ai pas trouvé de ressource claire sur les bonnes pratiques pour gérer une librairie publique d'un côté et un site l'utilisant dans une version potentiellement amendée, et j'ai l'impression que tout le monde re-développe un peu son outillage.

Une possibilité est d'utiliser un sous-module git référençant publicodes dans le dépôt mon-entreprise. On n'utiliserait donc pas une version de la librairie téléchargée depuis npm mais une version locale que l'on pourrait modifier, tout comme actuellement. Le dépôt mon-entreprise resterait un "mono-repo".

- Si on veut modifier uniquement le moteur, on peut créer une branche et ouvrir une PR dans le dépôt `publicodes`.
- Si on veut modifier le site mon-entreprise en amendant le moteur, on devra créer une branche sur publicodes et une branche sur mon-entreprise et mettre à jour le sous-module en conséquence (à moins qu'une branche `publicodes` ne soit pas nécessaire et que l'on puisse fonctionner uniquement avec des "commits orphelins" référencés via le sous-module ?). Ça demande un peu de manipulation mais que l'on pourra scripter. Seule une PR devra être ouverte sur mon-entreprise, car le but ne sera pas d'intégrer le changement sur le `master` de publicodes dans l'immédiat. Il faudra ré-intégrer les changements sur le `master` de publicodes dans un second temps.

Le process exact devra sans doute être affiné avec la pratique — et peut-être suis-je passé à côté d'outils tout faits qui nous faciliteraient la vie ?

À faire :
- [ ] Séparer la configuration des sites publi.codes et mon-entreprise.fr betagouv/publicodes#31
- [ ] Intégrer les traductions de la documentation dans le paquet `publicodes-react` #24
- [x] Copier les fichiers racines dont on aura besoin dans le dépôt publicodes (licence, `.gitignore`, config prettier, etc.)
- [x] Ajouter des actions GitHub pour le déploiement du site publi.codes et pour l'intégration continue. Je pense qu'en plus des tests publicodes il faudra exécuter les tests de non-regressions de mon-entreprise (et potentiellement d'autres bases de règles comme ecolab-data) lors d'une modification du moteur (grossièrement `git clone mon-entreprise && npm link publicdes && yarn run test:regressions`) #66
- [x] Extraire proprement l'historique git de publi.codes, en essayant de remonter le plus loin possible en suivant les déplacements et renommages de fichiers.
- [x] Déplacement effectif du code et des tickets
- [x] Configuration initiale du dépôt publicodes (règles des PR, branche `master` protégée, ouverture de la section "discussion", fermeture du wiki ?)

connexe betagouv/publicodes#18

**Comment by johangirod** [comment]
Je me met sur le point :  
>  Copier les fichiers racines dont on aura besoin dans le dépôt publicodes (licence, .gitignore, config prettier, etc.)

Mon but est de pouvoir compiler publicodes et faire tourner les tests juste avec un `git clone && yarn && yarn test`.

**Comment by laem** [comment]
J'ai commencé ici : https://github.com/betagouv/publicodes/pull/65

Mon objectif : ajouter des tests pour mettre en valeur le problème de https://github.com/betagouv/publicodes/issues/33 puis le résoudre.

**Comment by mquandalle** [comment]
Il est maintenant possible de faire des modifications directement sur ce dépôt, l'historique, les issues, et les actions Github ont été transféré et il y a une issue ouverte concernant le site.
