### ISSUE TITLE
Spécifier le fonctionnement des variables manquantes

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#33]
Un effet de bord de la nouvelle implémentation de la désactivation par espace de noms est que certaines dépendances sont ajoutées aux "variables manquantes" alors qu'elle ne l'étaient pas avant, et qu'on ne les veut pas (pour des raisons qu'il reste à bien expliciter).

Conversations précédentes :
- comment éviter d'ajouter `formule: oui` sur les espaces de noms betagouv/mon-entreprise#1342
- comportent non intuitif et correction betagouv/publicodes#30
- système de type betagouv/publicodes#14 

Une autre remarque sur laquelle j'avais commencé à travailler, c'est que les variables manquantes n'ont pas besoin d'être calculées au sein de chaque mécanisme car la logique est toujours la même : `mergeMissings(...nodes)` où `nodes` est la liste des nœuds évalués dans la situation courante. La logique de "bonus" qu'ont utilise pour marquer l'importance relative de certaines variables manquantes comme ici :

```js
const conditition = this.evaluate(conditionNode)
if (condition) {
  const consequence = this.evaluate(consequenceNode)
}

return { missingsVariables : mergeMissings(bonus(condition), consequence) }
``` 

peut aussi être rendue générique en ajoutant systématiquement un "bonus" au premier argument de `mergeMissings` (voir en se basant sur l'arbre des dépendances mais ça complique sans doute inutilement l'algorithme).

Avant de travailler sur une refonte de l'implémentation, mettons-nous d'accord sur la manière dont devraient fonctionner les variables manquantes.

**Comment by johangirod** [comment]
> Comme on le voit, on n'a pas besoin de la valeur exacte du parent mais on veut seulement saveur si elle n'est pas "non applicable". Pour se faire on est obligés d'explorer les mécanismes de type "produit" (variations, applicable si, non applicable si) mais on peut ignorer ceux de type somme (grille, barème).

Doter publicodes d'une inférence de type statique solide réglerait ce problème. La dépendance au parent n'étant active que lorsque le type du parent contient "NON APPLICABLE" ou "FAUX".

**Comment by mquandalle** [comment]
Implémenté dans #189
