### ISSUE TITLE
Liens morts dans la doc

### ISSUE THREAD

**Issue by simogeo** [betagouv/publicodes#364]
Bonjour,

Je suis en train de travailler sur une déclinaison polynésienne de NGC et j'essaie de me familiariser avec NGC publicodes et l'écosystème général. 

Il y a de nombreux liens morts dans la doc notamment sur les mécanismes et la grammaire ([ici](https://github.com/betagouv/publicodes/wiki/Documentation#grammaire-des-expressions)). Pourriez-vous les mettre à jour ou me pointer les ressources utiles ? Merci !  

Notamment 

- https://github.com/betagouv/mon-entreprise/blob/master/source/engine/grammar.ne
- https://github.com/betagouv/mon-entreprise/blob/master/source/engine/known-mecanisms.yaml

**Comment by johangirod** [comment]
Bonjour. La documentation référencée ici est dépréciée, seul le site est maintenu à jour : https://publi.codes

**Comment by johangirod** [comment]
J'ai supprimé les pages plus d'actualité dans le wiki.

**Comment by simogeo** [comment]
Bonjour @johangirod et merci pour les précisions
