### ISSUE TITLE
Explication du mécanisme `remplace` sur /documentation

### ISSUE THREAD

**Issue by laem** [betagouv/publicodes#52]
Il faut que la /documentation explique le principe visuellement.
betagouv/mon-entreprise#765 

@johangirod désolé, pas eu le temps cette semaine pour m'en occuper...

**Comment by lajarre** [comment]
Je crois qu'il reste encore à documenter dans publi.codes/documentation/m%C3%A9canismes

**Comment by johangirod** [comment]
Mmmh, on l'a pas vraiment classé dans mécanisme mais dans principe de base du langage, où il est documenté.

En fait mécanisme = fonctions de base (l'équivalent de Math.abs, Array.filter, ou autre en javascript). Pour le reste c'est plus de la syntaxe (comme async await, function, ou autre en JS).

https://publi.codes/documentation/principes-de-base#remplacement

**Comment by lajarre** [comment]
Ok en effet, pas trop convaincu de la présentation pour l'instant mais pas prio
