### ISSUE TITLE
Rendre l'exemple publicodes-react indépendant (dans un dépôt)

### ISSUE THREAD

**Issue by lajarre** [betagouv/publicodes#62]

**Comment by laem** [comment]
@lajarre Est-ce qu'on parle ici du paquet React actuel qui affiche la documentation, ou d'un autre paquet qui afficherait aussi la conversation ?

**Comment by lajarre** [comment]
En fait il s'agit du dossier example/publicodes-react qui est lui-même une app React indépendante. Je proposais cela pour pouvoir plus facilement le clone/checkout et le rendre mieux visible sur Github (à débattre).

**Comment by mquandalle** [comment]
Je trouve ça bien de garder tous les exemples dans le dépôt principal, ça permet de les maintenir à jour plus facilement, ainsi que de les intégrer facilement comme tests d'intégration.

C'est ce que fait par exemple Vercel / Next.js https://github.com/vercel/examples/tree/main/edge-functions/ab-testing-simple

Le CLI de Next.js permet facilement de cloner un exemple : 

```sh
npx create-next-app --example https://github.com/vercel/examples/tree/main/edge-functions/ab-testing-simple ab-testing-simple
```

J'ai l'impression que ce n'est pas aussi simple pour `npx create-react-app`, mais on doit quand même pouvoir trouver une commande qui clone le sous répertoire en une ligne.
