### ISSUE TITLE
Évaluation des règles affichées dans les pages de documentation

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#63]
L'évaluation de Publicode est paresseuse et lorsqu'on explore la documentation d'un calcul, certaines branches n'ont pas de valeurs affichées.

Je trouve ça un peu perturbant dans la documentation, il me semble plus logique de ré-évaluer l'ensemble des éléments affichés sur la page courante (ce qui n'est pas couteux grâce à la mise en cache des calculs).

**Comment by mquandalle** [comment]
@johangirod Tu disais que tu avais corrigé ça ?

**Comment by johangirod** [comment]
Oui, c'est avec ce bout de code : 
https://github.com/betagouv/publicodes/blob/master/packages/react-ui/source/Explanation.tsx#L62-L69

Introduit dans https://github.com/betagouv/publicodes/commit/2608725c0b403af51fc6f42844f9e8460d32f3f4

**Comment by mquandalle** [comment]
C'est top !
