### ISSUE TITLE
Bug sur les exemples de mécanisme dans la doc

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#78]
Ici : 
![Screenshot 2021-09-13 at 18-08-08 Dépenses primeur](https://user-images.githubusercontent.com/1775934/133118844-148a5a22-c97c-45c2-b010-4fc4e510db16.png)
Ou là : 
![Screenshot 2021-09-13 at 18-07-57 Dépenses primeur](https://user-images.githubusercontent.com/1775934/133118853-ba19b408-e546-4b7c-8d3d-0ebe8fc67988.png)

Je ne sais pas trop d'où ça vient, je n'ai pas regardé

**Comment by laem** [comment]
@johangirod j'ai l'impression que c'est l'utilisation du `>-` plutôt que du `|-` qui supprime les line breaks. 
CF https://stackoverflow.com/a/21699210

Je peux le corriger, mais je me demande où on en est côté publicodes : je peux cloner ce dépot et faire tourner le site, ou alors ça passe toujours par betagouv/mon-entreprise ?  cc @mquandalle
