### ISSUE TITLE
Conversion automatique des unités dans les mécanisme minimum / maximum

### ISSUE THREAD

**Issue by johangirod** [betagouv/publicodes#80]
## Problème

```
a: 
  le minimum de:
    - 1 mois
    - 7 jour
```

`a` vaut ici `0.23 mois`. On s'attendait à ce qu'il vaille `7 jour`

[Voir dans publicodes studio](https://publi.codes/studio/a?code=a%3A%20%0A%20%20le%20minimum%20de%3A%0A%20%20%20%20-%201%20mois%0A%20%20%20%20-%207%20jour%0A%20%20%20%20)

## Explication
Celà est dû à la fonction [`evaluateArray`](https://github.com/betagouv/publicodes/blob/master/core/source/evaluation.ts#L58). Cette dernière converti tous les éléments de la liste dans la même unité avant d'effectuer l'opération donnée en argument.

## Solution
Au lieu de faire un `reduce` uniquement sur les valeurs, il faudrait prendre en compte également les unités. La fonction publicodes à reducer serait : `(a, b) => 'si ${a} > ${b} alors ${b} sinon ${a}'`.

Cette issue sera donc automatiquement résolue lorsque #23 sera implémenté.

Test

**Comment by maxgfr** [comment]
+1

**Comment by maxgfr** [comment]
> `(a, b) => 'si ${a} > ${b} alors ${b} sinon ${a}'`

La solution que tu proposes a permise de corriger notre problème

Merci ! 🔥

**Comment by johangirod** [comment]
Résolu !
