### ISSUE TITLE
Faire ruisseler les références

### ISSUE THREAD

**Issue by laem** [betagouv/publicodes#87]
Comme suggéré [ici](https://github.com/betagouv/publicodes/issues/81#issuecomment-950799804), on a souvent je trouve le besoin de mettre des `références` dans un parent, tout en ayant une référence (!) vers cette `référence` dans la page /documentation d'une règle fille. 

> Je pensais avoir fait une issue pour améliorer la doc et répondre à ce problème, mais je la retrouve pas. L'idée était que la variable A . B, si B ne contient pas de références, aille rechercher la ref de A ou d'un parent encore plus lointain, avec un affichage du genre *le parent A a ces références*.

C'est assez simple à implémenter dans l'interface Web de publicodes.

**Comment by mquandalle** [comment]
Avec la `beta.17` on peut donner un composant `References` à la documentation. Cela permet d'implémenter cette fonctionnalité côté client, avec une logique du type

```jsx
// pseudo-code
function References() {
  const currentRuleName = getRuleName() // Probablement depuis un contexte React car pas exposé au composant ?
  const firstParentWithReference = getParents(currentRuleName).find(ruleName => engine.getRule(ruleName).rawRule.references)
  
  return /* render references */
}
```

C'est pas parfait mais ça me semble quand même intéressant que ça puisse être fait côté utilisateur, d'autant que le comportement désiré peut varier selon les applications (Est-ce qu'on s'arrête au premier parent qui a une référence ou bien on fusionne les références de tous les parents ? Quelle présentation ?)

**Comment by laem** [comment]
Oui très bonne idée. Je note ça pour quand j'aurai le temps de faire une passe sur l'affichage de la doc :)

**Comment by johangirod** [comment]
C'est effectivement une fonctionnalité implémentée par les différents réutilisateurs, en fonction de leur cas d'usage.
