### ISSUE TITLE
Documentation : espace de nom dans la liste des données manquantes

### ISSUE THREAD

**Issue by mquandalle** [betagouv/publicodes#95]
Sur l'exemple par défaut du [bac à sable publicodes](https://publi.codes/studio/d%C3%A9penses-primeur?code=%0A%23%20Bienvenue%20dans%20le%20bac%20%C3%A0%20sable%20du%20langage%20publicodes%20!%0A%23%20Pour%20en%20savoir%20plus%20sur%20le%20langage%20%3A%0A%23%20%3D%3E%20https%3A%2F%2Fpubli.codes%2Fdocumentation%2Fprincipes-de-base%0A%0Aprix%3A%0Aprix%20.%20carottes%3A%202%E2%82%AC%2Fkg%0Aprix%20.%20champignons%3A%205%E2%82%AC%2Fkg%0Aprix%20.%20avocat%3A%202%E2%82%AC%2Favocat%0A%0Ad%C3%A9penses%20primeur%3A%0A%20%20formule%3A%0A%20%20%20%20somme%3A%0A%20%20%20%20%20%20-%20prix%20.%20carottes%20*%201.5%20kg%0A%20%20%20%20%20%20-%20prix%20.%20champignons%20*%20500g%0A%20%20%20%20%20%20-%20prix%20.%20avocat%20*%203%20avocat%0A), la règle `prix` est affichée comme donnée manquante, alors que ce n'est pas le cas.

![image](https://user-images.githubusercontent.com/1730702/140491678-51ce8ac9-0c70-44c3-8980-ba9afb360090.png)

**Comment by lajarre** [comment]
Comment identifier un espace de nom de manière fiable? Peut-être en vérifiant, pour une règle donnée, si elle ne contient aucun mécanisme en clé du yaml dans sa version raw?

**Comment by johangirod** [comment]
Relié : #85
