### ISSUE TITLE
Données manquantes trop lourd sur les pages de /documentation

### ISSUE THREAD

**Issue by laem** [betagouv/publicodes#97]
![image](https://user-images.githubusercontent.com/1177762/140768938-80f48303-7ab8-4213-a29c-250d6140baec.png)

On pourrait simplement dans un 1er temps les mettre dans un `<details />`

<details> <summary>Données manquantes</summary>
A
B
C

</details>

**Comment by lajarre** [comment]
J'ai rajouté un petit commit https://github.com/betagouv/mon-entreprise/pull/1665/commits/67f5d532f327f7a886dbddbe8bf0100c2788ffdd en ce sens dans ma PR sur mon-entreprise qui traitait d'un sujet proche https://github.com/betagouv/mon-entreprise/pull/1665

**Comment by johangirod** [comment]
fixed by #261
